### ISSUE TITLE
Results for dance-twirl

### ISSUE THREAD

**Issue by iris112358** [gengshan-y/viser-release#3]
Hi, Thanks for open-sourcing this awesome work. I tried to run on the dance-twirl video and got the following results:

https://user-images.githubusercontent.com/96632902/152095343-c2fc9026-7835-468a-be92-a2114da35bf1.mp4

It seems the rendered frame does not match the input frame, I organized the data as suggested in the Readme and run by the command `sh scripts/dance-twirl.sh` and test by `bash scripts/render_result.sh dance-twirl  log/dance-twirl-1003-ft2/pred_net_latest.pth` --catemodel --cnnpp `, could you please let me know if this result is expected or if there's something wrong? Thanks!

**Comment by gengshan-y** [comment]
The args passed to the bash script seems wrong.
Can you run 
```
bash scripts/render_result.sh dance-twirl log/dance-twirl-1003-ft2/pred_net_latest.pth 36
```
instead?

**Comment by iris112358** [comment]
It works now. Thanks! BTW, is it possible to use an existing template for this model?

**Comment by gengshan-y** [comment]
The sphere template is loaded [here](https://github.com/gengshan-y/viser-release/blob/a3943ad80d391f1b60379524de3c5d07f924c6bd/nnutils/mesh_net.py#L136-L143). You can replace it with another template mesh.

You might need to tune other parameters to make it work, e.g., freezing the shape and only optimize cameras for the first few epochs.

**Comment by iris112358** [comment]
> The sphere template is loaded [here](https://github.com/gengshan-y/viser-release/blob/a3943ad80d391f1b60379524de3c5d07f924c6bd/nnutils/mesh_net.py#L136-L143). You can replace it with another template mesh.
> 
> You might need to tune other parameters to make it work, e.g., freezing the shape and only optimize cameras for the first few epochs.

I see. Thanks!
