### ISSUE TITLE
About the evaluation.

### ISSUE THREAD

**Issue by phamtrongthang123** [gengshan-y/viser-release#9]
Hi, thanks for publishing this wonderful works.

I want to ask is it possible for us to use the evalutation code from LASR to evaluate the ViSER's outputs? I think that it is possible, but I don't see you publish the evaluation code. Therefore, I think there is something that I haven't noticed. 
Thank you very much.

**Comment by gengshan-y** [comment]
The evaluation code/data for viser need some efforts to clean up. It's not in the short term plan. If you need anything specific, let me know by email.
